version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: marketmindai_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-marketmindai}
      POSTGRES_USER: ${POSTGRES_USER:-marketmindai}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-marketmindai123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - marketmindai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-marketmindai}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: marketmindai_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - marketmindai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: marketmindai_backend
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-marketmindai}:${POSTGRES_PASSWORD:-marketmindai123}@postgres:5432/${POSTGRES_DB:-marketmindai}
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-jwt-key-change-this-in-production}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-}
      - SMTP_USE_TLS=true
      - APP_NAME=MarketMindAI
      - APP_URL=${APP_URL:-http://localhost:3000}
      - API_URL=${API_URL:-http://localhost:8001}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - marketmindai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: marketmindai_frontend
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL:-http://localhost:8001}
      - REACT_APP_APP_NAME=MarketMindAI
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - marketmindai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  marketmindai-network:
    driver: bridge